#!/bin/bash
# v0.14

set +e  # Continue on error (do not halt)

echo "Running post-installation script..."
export DEBIAN_FRONTEND=noninteractive

# Configure STYX repository
curl -fsSL https://styx-firewall.github.io/styx-repo/styx-firewall-keyring.gpg | tee /usr/share/keyrings/styx-firewall-keyring.gpg >/dev/null
chmod 644 /usr/share/keyrings/styx-firewall-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/styx-firewall-keyring.gpg] https://styx-firewall.github.io/styx-repo trixie main" | tee /etc/apt/sources.list.d/styx.list
chmod 644 /etc/apt/sources.list.d/styx.list

# Clean package cache
apt-get clean

# Create user 'admin' with password 'admin'
if ! id admin &>/dev/null; then
    useradd -m -s /bin/bash admin
    echo "admin:admin" | chpasswd
fi

apt-get update
# Ensure styx-conf is installed
apt-get install -y styx-conf

# Copy custom initial config files (copy only if source exists)
CFG_DIR=/var/lib/styx/configs

# Ensure common destination directories exist
mkdir -p /etc/ssh /etc/lighttpd /etc/lighttpd/conf-available /etc/logrotate.d

copy_if_exists() {
  src="$1"
  dst="$2"
  if [ -e "$src" ]; then
    echo "Copying $src -> $dst"
    cp "$src" "$dst"
  else
    echo "Warning: $src not found, skipping copy to $dst"
  fi
}

copy_if_exists "$CFG_DIR/ulogd.conf" /etc/ulogd.conf
chmod 640 /etc/ulogd.conf
copy_if_exists "$CFG_DIR/sshd_config" /etc/ssh/sshd_config
chmod 600 /etc/ssh/sshd_config
copy_if_exists "$CFG_DIR/logrotate.conf" /etc/logrotate.conf
chmod 644 /etc/logrotate.conf
copy_if_exists "$CFG_DIR/lr-ulogd2" /etc/logrotate.d/ulogd2
chmod 644 /etc/logrotate.d/ulogd2
copy_if_exists "$CFG_DIR/os-release" /etc/os-release
chmod 644 /etc/os-release
# copy_if_exists "$CFG_DIR/journald.conf" /etc/systemd/journald.conf
copy_if_exists "$CFG_DIR/motd" /etc/motd
chmod 644 /etc/motd
copy_if_exists "$CFG_DIR/issue" /etc/issue
chmod 644 /etc/issue
copy_if_exists "$CFG_DIR/lighttpd.conf" /etc/lighttpd/lighttpd.conf
chmod 644 /etc/lighttpd/lighttpd.conf
copy_if_exists "$CFG_DIR/lighttpd-ssl.conf" /etc/lighttpd/conf-available/10-ssl.conf
chmod 644 /etc/lighttpd/conf-available/10-ssl.conf
copy_if_exists "$CFG_DIR/rsyslog.conf" /etc/rsyslog.conf
chmod 644 /etc/rsyslog.conf

mkdir -p /etc/styx
chmod 700 /etc/styx
copy_if_exists "$CFG_DIR/certs.json" /etc/styx/certs.json
chmod 600 /etc/styx/certs.json

mkdir -p /etc/systemd/system/tmp.mount.d
copy_if_exists "$CFG_DIR/tmp.conf" /etc/systemd/system/tmp.mount.d/override.conf
chmod 644 /etc/systemd/system/tmp.mount.d/override.conf

# Be sure services are enabled
systemctl enable ssh
systemctl enable ulogd2
systemctl enable logrotate
# not systemd file
# systemctl enable udhcpc ;
systemctl enable lighttpd
systemctl enable styx-gateway

# Enable tmpfs for /tmp
systemctl unmask tmp.mount 2>/dev/null
systemctl enable tmp.mount

# Generate self-signed SSL cert for lighttpd
IPS=$(hostname -I | awk '{for(i=1;i<=NF;i++) printf "IP:"$i","}' | sed 's/,$//')
mkdir -p /etc/ssl/local-private
mkdir -p /etc/ssl/local-certs
chmod 700 /etc/ssl/local-private
chmod 755 /etc/ssl/local-certs

openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
  -keyout /etc/ssl/local-private/https-privkey.pem  -out /etc/ssl/local-certs/https-cert.pem  \
  -subj "/C=XX/ST=Autogenerated/L=Autogenerated/O=Styx Example Self-Signed/OU=Autogenerated Certificate/CN=styx-gateway.local" \
  -addext "subjectAltName=DNS:styx-gateway.local,$IPS" \
  -addext "extendedKeyUsage=serverAuth" \
  -addext "keyUsage=digitalSignature, keyEncipherment"

# Set secure permissions for private key and certificate (only if files exist)

if [ -e /etc/ssl/local-private/https-privkey.pem ]; then
  chmod 600 /etc/ssl/local-private/https-privkey.pem
else
  echo "Warning: /etc/ssl/local-private/https-privkey.pem not found; skipping chmod"
fi

if [ -e /etc/ssl/local-certs/https-cert.pem ]; then
  chmod 644 /etc/ssl/local-certs/https-cert.pem
else
  echo "Warning: /etc/ssl/local-certs/https-cert.pem not found; skipping chmod"
fi

# Enable SSL and php in lighttpd
lighttpd-enable-mod fastcgi
lighttpd-enable-mod fastcgi-php-fpm
lighttpd-enable-mod ssl


# Clean
apt remove --purge -y laptop-detect
apt remove --purge -y dhcpcd-base
# Make sure default meta-package is removed to avoid unwanted upgrades
apt remove --purge -y linux-image-amd64
#apt autoremove --purge -y
# Trigger update-grub due to os-release change
update-grub

#umount /home
#e2fsck -f -y /dev/vg_styx/home
#resize2fs /dev/vg_styx/home 500M
#lvreduce -L 512M /dev/vg_styx/home
#mount /home

# Compliance
systemctl mask ctrl-alt-del.target

# Blacklist unused/unwanted kernel modules for security hardening
BLACKLIST_DIR=/etc/modprobe.d
mkdir -p "$BLACKLIST_DIR"

BLACKLIST_MODULES=(
  sctp
  dccp
  cramfs
  freevxfs
  jffs2
  hfs
  hfsplus
  squashfs
  udf
)

for mod in "${BLACKLIST_MODULES[@]}"; do
  conf_file="$BLACKLIST_DIR/${mod}.conf"
  cat > "$conf_file" <<EOF
# ${mod} – blacklisted for security hardening
blacklist ${mod}
install ${mod} /bin/false
EOF
  chmod 644 "$conf_file"
done

echo "Blacklisted kernel modules: ${BLACKLIST_MODULES[*]}"


# ---------------------------------------------------------------------------
# Journal directory permissions – ensure mode 2750 (owner rwx, group r-x,
# others ---) so that others cannot read journal logs.
# ---------------------------------------------------------------------------

echo "Hardening journal directory permissions to 2750..."

# 1) Fix existing directories now (remove ACLs then set mode)
chmod 2750 /var/log/journal 2>/dev/null || true
find /var/log/journal -type d -exec setfacl -b {} \; -exec chmod 2750 {} \; 2>/dev/null || true

chmod 2750 /run/log/journal 2>/dev/null || true
find /run/log/journal -type d -exec setfacl -b {} \; -exec chmod 2750 {} \; 2>/dev/null || true

# 2) Ensure /run/log/journal is recreated with 2750 on every boot
mkdir -p /etc/tmpfiles.d
cat > /etc/tmpfiles.d/journal-perms.conf <<'EOF'
# Ensure journal directories are created with mode 2750
d /run/log/journal 2750 root systemd-journal -
d /run/log/journal/%m 2750 root systemd-journal -
EOF
chmod 644 /etc/tmpfiles.d/journal-perms.conf

# Apply tmpfiles immediately
systemd-tmpfiles --create /etc/tmpfiles.d/journal-perms.conf 2>/dev/null || true

# 3) Force restrictive umask for systemd-journald so any directory or file it
#    creates (rotated journals, subdirs, etc.) can never be world-readable.
mkdir -p /etc/systemd/system/systemd-journald.service.d
cat > /etc/systemd/system/systemd-journald.service.d/umask.conf <<'EOF'
[Service]
UMask=0027
EOF
chmod 644 /etc/systemd/system/systemd-journald.service.d/umask.conf
systemctl daemon-reload 2>/dev/null || true

echo "Journal directory permissions set to 2750"

# Add systemd override for ulogd2 to set UMask and Group
mkdir -p /etc/systemd/system/ulogd2.service.d
cat > /etc/systemd/system/ulogd2.service.d/override.conf <<'EOF'
[Service]
UMask=0027
Group=adm
EOF
chmod 644 /etc/systemd/system/ulogd2.service.d/override.conf
systemctl daemon-reload 2>/dev/null || true

# Install
apt-get -o Dpkg::Options::="--force-confold" install -y chrony
apt-get -o Dpkg::Options::="--force-confold" install -y rsyslog
# Utils
apt-get -o Dpkg::Options::="--force-confold" install -y ccze

# Clean /var/log
rm -f /var/log/README
# BPF tools
#apt-get install  bpfcc-tools libbpfcc libbpfcc-dev