#!/bin/bash
# v0.9

echo "Running post-installation script..."

# Configurar repositorio STYX
curl -fsSL https://styx-firewall.github.io/styx-repo/styx-firewall-keyring.gpg | tee /usr/share/keyrings/styx-firewall-keyring.gpg >/dev/null
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/styx-firewall-keyring.gpg] https://styx-firewall.github.io/styx-repo trixie main" | tee /etc/apt/sources.list.d/styx.list

# Limpiar caché de paquetes
apt-get clean

# Crear usuario 'admin' con contraseña 'admin'
if ! id admin &>/dev/null; then
    useradd -m -s /bin/bash admin
    echo "admin:admin" | chpasswd
fi

apt-get update -y
# Assure styx-conf is installed
apt-get install -y styx-conf

# Copy custom initial config files (copy only if source exists)
CFG_DIR=/var/lib/styx/configs

# Ensure common destination directories exist
mkdir -p /etc/ssh /etc/lighttpd /etc/lighttpd/conf-available /etc/logrotate.d

copy_if_exists() {
  src="$1"
  dst="$2"
  if [ -e "$src" ]; then
    echo "Copying $src -> $dst"
    cp "$src" "$dst"
  else
    echo "Warning: $src not found, skipping copy to $dst"
  fi
}

copy_if_exists "$CFG_DIR/ulogd.conf" /etc/ulogd.conf
copy_if_exists "$CFG_DIR/sshd_config" /etc/ssh/sshd_config
copy_if_exists "$CFG_DIR/logrotate.conf" /etc/logrotate.conf
copy_if_exists "$CFG_DIR/lr-ulogd2" /etc/logrotate.d/ulogd2
copy_if_exists "$CFG_DIR/os-release" /etc/os-release
# copy_if_exists "$CFG_DIR/journald.conf" /etc/systemd/journald.conf
copy_if_exists "$CFG_DIR/motd" /etc/motd
copy_if_exists "$CFG_DIR/issue" /etc/issue
copy_if_exists "$CFG_DIR/lighttpd.conf" /etc/lighttpd/lighttpd.conf
copy_if_exists "$CFG_DIR/lighttpd-ssl.conf" /etc/lighttpd/conf-available/10-ssl.conf

# Be sure services are enabled
systemctl enable ssh
systemctl enable ulogd2
systemctl enable logrotate
# not systemd file
# systemctl enable udhcpc ;
systemctl enable lighttpd
systemctl enable styx-gateway

# Enable tmpfs for /tmp
systemctl unmask tmp.mount 2>/dev/null
systemctl enable tmp.mount

# Enable SSL and php in lighttpd
lighttpd-enable-mod fastcgi
lighttpd-enable-mod fastcgi-php-fpm
lighttpd-enable-mod ssl

# Generate self-signed SSL cert for lighttpd
IPS=$(hostname -I | awk '{for(i=1;i<=NF;i++) printf "IP:"$i","}' | sed 's/,$//')
mkdir -p /etc/ssl/local-private
mkdir -p /etc/ssl/local-certs
chmod 700 /etc/ssl/local-private
chmod 755 /etc/ssl/local-certs

openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
  -keyout /etc/ssl/local-private/https-privkey.pem  -out /etc/ssl/local-certs/https-cert.pem  \
  -subj "/C=XX/ST=Autogenerated/L=Autogenerated/O=Styx Example Self-Signed/OU=Autogenerated Certificate/CN=styx-gateway.local" \
  -addext "subjectAltName=DNS:styx-gateway.local,$IPS"

# Set secure permissions for private key and certificate (only if files exist)

if [ -e /etc/ssl/local-private/https-privkey.pem ]; then
  chmod 600 /etc/ssl/local-private/https-privkey.pem
else
  echo "Warning: /etc/ssl/local-private/https-privkey.pem not found; skipping chmod"
fi

if [ -e /etc/ssl/local-certs/https-cert.pem ]; then
  chmod 644 /etc/ssl/local-certs/https-cert.pem
else
  echo "Warning: /etc/ssl/local-certs/https-cert.pem not found; skipping chmod"
fi

# Clean
apt remove --purge -y laptop-detect
apt remove --purge -y dhcpcd-base
# Make sure default meta-package is removed to avoid unwanted upgrades
apt remove --purge -y linux-image-amd64

# Trigger update grub due os-release change
update-grub

# BPF tools
#apt-get install  bpfcc-tools libbpfcc libbpfcc-dev
