#!/bin/bash
# v0.8

set -e  # Detiene el script si hay errores
echo "Running post-installation script..."

# Configurar repositorio STYX
curl -fsSL https://styx-firewall.github.io/styx-repo/styx-firewall-keyring.gpg | tee /usr/share/keyrings/styx-firewall-keyring.gpg >/dev/null
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/styx-firewall-keyring.gpg] https://styx-firewall.github.io/styx-repo trixie main" | tee /etc/apt/sources.list.d/styx.list

# Limpiar caché de paquetes
apt-get clean

# Crear usuario 'admin' con contraseña 'admin'
if ! id admin &>/dev/null; then
    useradd -m -s /bin/bash admin
    echo "admin:admin" | chpasswd
fi

# Asure styx-conf is installed
apt-get install -y styx-conf

# Copy custom initial config files
cp /var/lib/styx/configs/ulogd.conf /etc/ulogd.conf
cp /var/lib/styx/configs/sshd_config /etc/ssh/sshd_config
cp /var/lib/styx/configs/logrotate.conf /etc/logrotate.conf
cp /var/lib/styx/configs/lr-ulogd2 /etc/logrotate.d/ulogd2
cp /var/lib/styx/configs/os-release /etc/os-release
# cp /var/lib/styx/configs/journald.conf /etc/systemd/journald.conf
cp /var/lib/styx/configs/motd /etc/motd
cp /var/lib/styx/configs/issue /etc/issue
cp /var/lib/styx/configs/lighttpd.conf /etc/lighttpd/lighttpd.conf
cp /var/lib/styx/configs/lighttpd-ssl.conf /etc/lighttpd/conf-available/10-ssl.conf

# Trigger update grub due os-release change
update-grub

# Be sure services are enabled
systemctl enable ssh
systemctl enable ulogd2
systemctl enable logrotate
systemctl enable udhcpc
systemctl enable lighttpd

# Enable SSL and php in lighttpd
lighttpd-enable-mod fastcgi
lighttpd-enable-mod fastcgi-php-fpm
lighttpd-enable-mod ssl

# Generate self-signed SSL cert for lighttpd
IPS=$(hostname -I | awk '{for(i=1;i<=NF;i++) printf "IP:"$i","}' | sed 's/,$//')
openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
  -keyout /etc/ssl/private/https-privkey.pem  -out /etc/ssl/certs/https-fullchain.pem  \
  -subj "/C=XX/ST=Autogenerated/L=Autogenerated/O=Styx Example Self-Signed/OU=Autogenerated Certificate/CN=styx-gateway.local" \
  -addext "subjectAltName=DNS:styx-gateway.local,$IPS"

# Clean
apt remove --purge -y latptop-detect
apt remove --purge -y dhcpcd-base
# Make sure default meta-package is removed to avoid unwanted upgrades
apt remove --purge -y linux-image-amd64

# Reload services
systemctl daemon-reload
systemctl restart ssh
systemctl restart ulogd2
systemctl restart logrotate
systemctl restart udhcpc
systemctl restart lighttpd

# BPF tools
#apt-get install  bpfcc-tools libbpfcc libbpfcc-dev
